version: "3.9"
services:

  backend:
    build:
      context: .
    networks:
      - server-side
      - client-side
    env_file:
      - .env.backend
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.1
    restart: always
    user: postgres
    networks:
      - server-side
    env_file:
      - .env.database
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  server-side: {}
  client-side: {}

volumes:
  postgres-data: {}