version: "3.9"
services:

  backend:
    build:
      context: .
    networks:
      - server-side
      - client-side
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.1
    restart: always
    user: postgres
    networks:
      - server-side
    secrets:
      - db-password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
secrets:
  db-password:
  # because of this issue: https://github.com/docker/compose/issues/8305
  # if this file is missing there will be no warning but the container will break if you're using windows
    file: secrets/db-password

networks:
  server-side: {}
  client-side: {}

volumes:
  postgres-data: {}